---
    - name: Enable systemd in WSL
      become: yes
      ini_file:
        path: /etc/wsl.conf
        section: boot
        option: systemd
        value: "true"
        no_extra_spaces: true
        create: yes
        mode: "0644"
        backup: yes
    - name: Message to restart WSL
      debug:
        msg: "Redémarre WSL: wsl --shutdown (dans PowerShell) puis relance Ubuntu."
