---
- hosts: local
  connection: local
  gather_facts: yes

  vars:
    user_home: "{{ lookup('env', 'HOME') }}" 
      
  tasks:
    - name: Update APT cache
      become: true
      apt:
        update_cache: yes

    - name: Install bare minimum for devcontainer & editing
      become: true
      apt:
        state: present
        pkg:
          - git
          - openssh-client
          - curl
          - ca-certificates
          - unzip
          - nano
          - tmux
    

    - name: Drop a minimal tmux config
      become: false
      copy:
        src: "{{ playbook_dir }}/files/tmux.conf" 
        dest: "{{ user_home }}/.tmux.conf"
        mode: "0644"

    - name: Reload tmux config
      become: false
      shell: |
        tmux ls > dev/null 2>&1 && tmux source-file "{{ user_home }}/.tmux.conf" || true
      args:
        executable: /bin/bash
      changed_when: false

    - name: Create a workspace folder
      file:
        path: "{{user_home}}/source"
        state: directory
        mode: '0755'
