---
- hosts: local
  gather_facts: yes
  vars:
    user_home: "{{ ansible_env.HOME }}"
      
  tasks:
    - name: Update APT cache
      become: true
      apt:
        update_cache: yes

    - name: Ensure default tmux (no custom config)
      become: false
      file:
        path: "{{ ansible_env.HOME }}/.tmux.conf"
        state: absent
    
    - name: Install bare minimum for devcontainer & editing
      become: true
      apt:
        state: present
        pkg:
          - git
          - openssh-client
          - curl
          - ca-certificates
          - unzip
          - nano
          - tmux
    

    - name: Drop a minimal tmux config
      become: false
      tags: 
        - tmux-config
      copy:
        dest: "{{ user_home }}/.tmux.conf"
        mode: "0644"
        content: |
          set -g mouse on
          setw -g mode-keys vi
          bind -n C-h select-pane -L
          bind -n C-j select-pane -D
          bind -n C-k select-pane -U
          bind -n C-l select-pane -R

    - name: Create a workspace folder
      file:
        path: "{{user_home}}/source"
        state: directory
        mode: '0755'
