---
- hosts: local
  gather_facts: yes
  become: yes

  tasks:
    - name: Enable systemd in WSL
      blockinfile:
        path: /etc/wsl.conf
        create: yes
        block: |
          [boot]
          systemd=true
    - name: Message to restart WSL
      debug:
        msg: "Redémarre WSL: wsl --shutdown (dans PowerShell) puis relance Ubuntu."